In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_sample_image
from sklearn.datasets import load_digits
from sklearn.cluster import KMeans
from sklearn.metrics import confusion_matrix, accuracy_score
from scipy.stats import mode

digits = load_digits()
X = digits.data

y = digits.target

k_means = KMeans(n_clusters=10)
predict = k_means.fit_predict(X)

In [2]:
labels = np.zeros_like(predict)
for i in range(10):
    mask = (predict==i)
    labels[mask] = mode(y[mask])[0]

print("Accuracy Score: ", accuracy_score(y,labels))
print("\nConfusion Matrix: \n", confusion_matrix(y, labels))

Accuracy Score:  0.7952142459654981

Confusion Matrix: 
 [[177   0   0   0   1   0   0   0   0   0]
 [  0  55  24   1   0   1   2   0  99   0]
 [  1   2 148  13   0   0   0   3   8   2]
 [  0   0   0 154   0   2   0   7   7  13]
 [  0   5   0   0 165   0   0   7   4   0]
 [  0   0   0   1   2 136   1   0   0  42]
 [  1   1   0   0   0   0 177   0   2   0]
 [  0   0   0   0   0   0   0 175   4   0]
 [  0   5   3   2   0   5   2   3 103  51]
 [  0  20   0   6   0   6   0   7   2 139]]


In [8]:
from sklearn.datasets import load_sample_image
img=load_sample_image('gg.jpg')
type(img)
img.shape

ImportError: The Python Imaging Library (PIL) is required to load data from jpeg files

In [4]:
l,h,d=img.shape
img_arr=np.reshape(img,(l*h,d))
model = KMeans(n_clusters=7)
fimg = model.fit(img_arr)

NameError: name 'img' is not defined

In [5]:
labels = model.predict(img_arr)

NameError: name 'model' is not defined

In [6]:
a=np.reshape(labels,(427,640))
plt.imshow(a)

ValueError: cannot reshape array of size 1797 into shape (427,640)