In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits 
digit = load_digits()
digit.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [2]:
x = digit.data
print(x)
y = digit.target
print(y)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
[0 1 2 ... 8 9 8]


In [3]:
from sklearn.preprocessing import StandardScaler
x_std = StandardScaler().fit_transform(x) 
x_std

array([[ 0.        , -0.33501649, -0.04308102, ..., -1.14664746,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  0.54856067,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  1.56568555,
         1.6951369 , -0.19600752],
       ...,
       [ 0.        , -0.33501649, -0.88456568, ..., -0.12952258,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -0.67419451, ...,  0.8876023 ,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649,  1.00877481, ...,  0.8876023 ,
        -0.26113572, -0.19600752]])

In [4]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train, y_test = train_test_split(x_std , y ,test_size = 0.4, random_state = 20)
from sklearn.decomposition import PCA
pca = PCA(n_components = 0.96 )
x_train = pca.fit_transform(x_train)
x_test = pca.transform(x_test)
from sklearn.linear_model import LogisticRegression
log = LogisticRegression()
log.fit(x_train , y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [6]:
prediction = log.predict(x_test)

from sklearn.metrics import accuracy_score
acv=accuracy_score(y_test , prediction)
print('*'*100)
print('accuracy_score\n')
print(acv)
from sklearn.metrics import confusion_matrix
acon=confusion_matrix(y_test , prediction)
print('*'*100)
print('confusion_matrix\n')
print(acon)

****************************************************************************************************
accuracy_score

0.9541029207232267
****************************************************************************************************
confusion_matrix

[[63  0  0  0  0  0  0  0  0  0]
 [ 0 72  0  1  0  0  0  0  1  1]
 [ 0  0 63  0  0  0  0  0  0  0]
 [ 0  0  0 73  0  3  0  1  3  0]
 [ 0  1  0  0 72  0  0  1  0  1]
 [ 1  0  0  0  0 70  0  0  0  0]
 [ 0  0  0  0  2  0 69  0  0  0]
 [ 0  0  0  1  0  0  0 78  0  1]
 [ 0  2  0  0  0  1  1  1 58  1]
 [ 0  1  0  0  0  1  0  1  6 68]]


In [7]:
from sklearn.metrics import classification_report
classification_report(y_test , prediction,labels = None, digits = 3)

'             precision    recall  f1-score   support\n\n          0      0.984     1.000     0.992        63\n          1      0.947     0.960     0.954        75\n          2      1.000     1.000     1.000        63\n          3      0.973     0.912     0.942        80\n          4      0.973     0.960     0.966        75\n          5      0.933     0.986     0.959        71\n          6      0.986     0.972     0.979        71\n          7      0.951     0.975     0.963        80\n          8      0.853     0.906     0.879        64\n          9      0.944     0.883     0.913        77\n\navg / total      0.955     0.954     0.954       719\n'